import type {
  PlayBoardControlArea,
  PlayBoardFlow,
  PlayBoardPlane,
  PlayBoardScreen,
  PlayBoardStatus,
  PlayBoardWorkItem,
} from "./types";

export const playBoardPlanes = [
  {
    id: "b2c",
    title: "B2C 투자자 경험",
    description: "예산 입력부터 후보 구역 탐색, 구역 상세, 기축 대조군 비교까지의 핵심 사용자 흐름입니다.",
  },
  {
    id: "b2b",
    title: "B2B 파트너 경험",
    description: "3 Month MVP 이후 본격화할 파트너 흐름입니다. 현재 보드는 MVP 범위 추적을 우선합니다.",
  },
  {
    id: "ops",
    title: "운영·정책 관리",
    description: "LTV 정책, 관리자 화면, 데이터 큐레이션, Preview 검증 흐름입니다.",
  },
  {
    id: "system",
    title: "시스템 상태",
    description: "Empty state, 면책/데이터 기준일, 배포/환경 분리처럼 여러 화면이 참조하는 상태 표면입니다.",
  },
] satisfies PlayBoardPlane[];

export const playBoardStatuses = [
  { id: "planned", label: "기획확정", rank: 1, description: "계약과 문서가 확정됐고 구현 대기 중입니다." },
  { id: "partial", label: "부분구현", rank: 2, description: "화면 또는 데이터 흐름 일부가 구현됐습니다." },
  { id: "implemented", label: "구현·머지완료", rank: 3, description: "구현이 완료되어 머지 가능한 상태입니다." },
  { id: "verified", label: "검증완료", rank: 4, description: "자동/수동 검증까지 완료된 상태입니다." },
] satisfies PlayBoardStatus[];

export const playBoardScreens = [
  {
    plane: "b2c",
    slug: "landing-budget-search",
    title: "예산 범위 랜딩",
    route: "/",
    designSpecType: "service",
    flowNote: "사용자가 가용 현금 범위를 선택하고 Reverse Filter 결과로 진입합니다.",
    status: "verified",
    workItems: ["mvp-014", "mvp-024"],
    requirementRefs: ["docs/MVP_BUDGET_RANGE_LANDING260621.md", "docs/00_PRD_v0.1.md"],
    implLocation: "frontend/app/(b2c)/page.tsx; frontend/components/b2c/BudgetRangeSearch.tsx",
    demoStrategy: "real-route",
    engineering: {
      authGate: "공개 화면입니다.",
      clientActions: ["예산 quick range 선택", "결과 페이지 이동"],
      serverActions: [],
      dataReads: ["정적 랜딩 콘텐츠", "scatter preview mock data"],
      dataWrites: [],
      telemetryEvents: ["landing_search_started 예정"],
      exceptionStates: ["empty-results"],
      controlAreaNotes: {
        "ux-safety": "예산 범위는 1억~25억, 5천만 원 단위로 제한됩니다.",
        performance: "랜딩 LCP 1.0s 목표의 핵심 진입 화면입니다.",
        observability: "검색 완료율 KPI 계측 진입점입니다.",
      },
    },
  },
  {
    plane: "b2c",
    slug: "reverse-filter-results",
    title: "Reverse Filter 결과",
    route: "/app/results",
    designSpecType: "service",
    flowNote: "예산 범위에 맞는 구역 후보를 리스트와 시각화로 확인합니다.",
    status: "verified",
    workItems: ["mvp-012", "mvp-015", "mvp-016", "mvp-024"],
    requirementRefs: [
      "docs/MVP_REVERSE_FILTER_ACTION260621.md",
      "docs/MVP_REVERSE_FILTER_RESULTS260623.md",
      "docs/MVP_REVERSE_FILTER_RESULTS_FILTERS260623.md",
    ],
    implLocation: "frontend/app/app/results/page.tsx; frontend/components/b2c/ResultsScatterExplorer.tsx",
    demoStrategy: "real-route",
    engineering: {
      authGate: "공개 화면입니다.",
      clientActions: ["district/stage 필터", "정렬 변경", "구역 상세 이동", "같은 예산 기축단지 비교 이동"],
      serverActions: ["reverseFilterAction"],
      dataReads: ["zones", "zone_investment_snapshots", "ltv_policies"],
      dataWrites: [],
      telemetryEvents: ["reverse_filter_results_viewed 예정"],
      exceptionStates: ["empty-results", "data-disclosure"],
      controlAreaNotes: {
        "data-accuracy": "최신 구역 investment snapshot과 데이터 기준일을 결과에 노출합니다.",
        "finance-policy": "LTV 정책 존재 여부가 Reverse Filter 처리의 전제입니다.",
        "ux-safety": "예산 초과 구역은 기본 결과에서 제외하고 근접 후보만 보조 노출합니다.",
        performance: "Reverse Filter p95 1.5s 목표와 직접 연결됩니다.",
      },
    },
  },
  {
    plane: "b2c",
    slug: "zone-detail-lite",
    title: "구역 상세 Lite",
    route: "/app/zones/[id]",
    designSpecType: "service",
    flowNote: "선택한 구역의 기본 정보, 실투자금 범위, 기축 레퍼런스를 확인합니다.",
    status: "verified",
    workItems: ["mvp-019", "mvp-020", "mvp-024"],
    requirementRefs: ["docs/MVP_ZONE_DETAIL_LITE260624.md", "docs/MVP_REFERENCE_APARTMENT_CARD260624.md"],
    implLocation: "frontend/app/app/zones/[id]/page.tsx; frontend/components/domain/ReferenceApartmentComparisonCard.tsx",
    demoStrategy: "real-route",
    engineering: {
      authGate: "공개 화면입니다.",
      clientActions: ["검색 결과 복귀", "같은 예산 기축단지 비교 이동"],
      serverActions: ["Prisma zone/referenceApartment 조회"],
      dataReads: ["zones", "zone_investment_snapshots", "zone_reference_apartments", "reference_apartments"],
      dataWrites: [],
      telemetryEvents: ["zone_detail_viewed 예정"],
      exceptionStates: ["data-disclosure"],
      controlAreaNotes: {
        "data-accuracy": "구역의 최신 투자금 snapshot과 기축 레퍼런스 연결을 같은 화면에 표시합니다.",
        "ux-safety": "기축 레퍼런스와 같은 예산 대조군의 개념 차이를 분리합니다.",
      },
    },
  },
  {
    plane: "b2c",
    slug: "comparison-assets",
    title: "같은 실투자금 기축단지 비교",
    route: "/app/comparison/[id]",
    designSpecType: "service",
    flowNote: "구역 최소 실투자금으로 진입 가능한 기축 대조군과 LTV 가정을 비교합니다.",
    status: "verified",
    workItems: ["mvp-021", "mvp-022", "mvp-024"],
    requirementRefs: ["docs/MVP_COMPARISON_DATA_ACTION260624.md", "docs/MVP_SIMPLE_REPORT_SECTION260625.md"],
    implLocation: "frontend/app/app/comparison/[id]/page.tsx; frontend/lib/comparisonAssets.ts",
    demoStrategy: "real-route",
    engineering: {
      authGate: "공개 화면입니다.",
      clientActions: ["생애최초 70%/일반 40% LTV 모델 선택", "구역 상세 복귀"],
      serverActions: ["comparisonDataAction"],
      dataReads: ["zones", "zone_investment_snapshots", "comparison assets code dataset"],
      dataWrites: [],
      telemetryEvents: ["comparison_viewed 예정", "comparison_ltv_model_changed 예정"],
      exceptionStates: ["data-disclosure"],
      controlAreaNotes: {
        "data-accuracy": "DATA_CURATION_SPEC 3번의 Comparison Assets 기준을 UI 계약으로 사용합니다.",
        "finance-policy": "기축 대조군 필요 현금은 LTV 모델별 가정으로 계산합니다.",
        "ux-safety": "실제 대출 승인액이 아닌 MVP 가정치임을 고정 문구로 알립니다.",
      },
    },
  },
  {
    plane: "b2c",
    slug: "stage-cash-scatter",
    title: "사업 단계/실투자금 시각화",
    route: "/app/scatter",
    designSpecType: "content",
    flowNote: "사업 단계와 실투자금 분포를 별도 시각화 화면에서 탐색합니다.",
    status: "verified",
    workItems: ["mvp-016", "mvp-023"],
    requirementRefs: ["docs/MVP_REVERSE_FILTER_RESULTS_FILTERS260623.md", "docs/MVP_STAGE_CASH_VISUALIZATION260626.md"],
    implLocation: "frontend/app/app/scatter/page.tsx",
    demoStrategy: "real-route",
    engineering: {
      authGate: "공개 화면입니다.",
      clientActions: ["예산 필터", "구역 선택", "스캐터 탐색"],
      serverActions: [],
      dataReads: ["frontend/app/lib/scatterData.ts"],
      dataWrites: [],
      telemetryEvents: ["scatter_explorer_viewed 예정"],
      exceptionStates: [],
      controlAreaNotes: {
        "ux-safety": "사용자에게 점/대표 위치와 실제 실투자금 범위의 차이를 명확히 설명해야 합니다.",
      },
    },
  },
  {
    plane: "ops",
    slug: "ltv-policy",
    title: "LTV 정책 관리",
    route: "/ltv-policy",
    designSpecType: "operations",
    flowNote: "LTV 정책 파라미터를 확인하고 향후 운영자가 조정하는 화면입니다.",
    status: "implemented",
    workItems: ["mvp-009", "mvp-012"],
    requirementRefs: ["docs/MVP_LTV_POLICY_UTIL260621.md", "docs/MVP_SUPABASE_SCHEMA260621.md"],
    implLocation: "frontend/app/(admin)/ltv-policy/page.tsx; frontend/lib/ltvPolicy.ts",
    demoStrategy: "real-route",
    engineering: {
      authGate: "향후 Admin 인증 보호가 필요합니다.",
      clientActions: ["정책 조회"],
      serverActions: ["listActiveLtvPolicies"],
      dataReads: ["ltv_policies"],
      dataWrites: ["ltv_policies 예정"],
      telemetryEvents: ["admin_ltv_policy_viewed 예정"],
      exceptionStates: [],
      controlAreaNotes: {
        "finance-policy": "LTV/DSR 정책값 하드코딩 금지 원칙의 운영 표면입니다.",
        "security-access": "Admin 전용 화면으로 RBAC 적용이 필요합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "mvp-project-foundation",
    title: "MVP Project 기반",
    route: "GitHub Project #3",
    designSpecType: "system-state",
    flowNote: "3 Month MVP 전용 GitHub Project, 브랜치, Preview 운영 규칙을 추적합니다.",
    status: "verified",
    workItems: ["mvp-001", "mvp-002"],
    requirementRefs: ["docs/MVP_PREVIEW_WORKFLOW260621.md"],
    implLocation: "docs/MVP_PREVIEW_WORKFLOW260621.md",
    demoStrategy: "mock",
    engineering: {
      authGate: "운영 규칙 문서입니다.",
      clientActions: [],
      serverActions: [],
      dataReads: ["GitHub Project #3", "MVP issue labels"],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "preview-deploy": "3 Month MVP는 full-spec 89개 backlog와 분리된 Project #3 기준으로 관리합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "mvp-data-pipeline",
    title: "MVP 데이터 파이프라인",
    route: "docs/MVP_DATA_*",
    designSpecType: "system-state",
    flowNote: "컬럼 계약, Supabase schema, normalization, seed/upsert, 품질 리포트를 묶은 데이터 foundation입니다.",
    status: "verified",
    workItems: ["mvp-003", "mvp-004", "mvp-005", "mvp-006", "mvp-007", "mvp-008", "mvp-data-141"],
    requirementRefs: [
      "docs/MVP_DATA_COLUMN_CONTRACT260621.md",
      "docs/MVP_SUPABASE_SCHEMA260621.md",
      "docs/MVP_GOLDEN_SAMPLES_NORMALIZATION260621.md",
      "docs/MVP_NAVER_LAND_NORMALIZATION260621.md",
      "docs/MVP_SUPABASE_SEED_UPSERT260621.md",
      "docs/MVP_DATA_QUALITY_REPORT260621.md",
    ],
    implLocation: "frontend/prisma/schema.prisma; docs/MVP_*DATA*; docs/MVP_*NORMALIZATION*",
    demoStrategy: "mock",
    engineering: {
      authGate: "운영팀 데이터 큐레이션 영역입니다.",
      clientActions: [],
      serverActions: ["Prisma schema", "seed/upsert pipeline"],
      dataReads: ["CSV/XLSX source files", "normalized seed data"],
      dataWrites: ["Supabase Preview DB"],
      telemetryEvents: [],
      exceptionStates: ["data-disclosure"],
      controlAreaNotes: {
        "data-accuracy": "3 Month MVP 데이터 계약과 정규화 산출물을 추적합니다.",
        "preview-deploy": "Preview DB seed/upsert가 Production과 분리되어야 합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "core-calculation-tests",
    title: "핵심 계산/단위 테스트",
    route: "npm run test:core-business",
    designSpecType: "system-state",
    flowNote: "취득세, LTV, Reverse Filter DTO/Core 등 핵심 계산 테스트 묶음입니다.",
    status: "verified",
    workItems: ["mvp-010", "mvp-011", "mvp-013"],
    requirementRefs: [
      "docs/MVP_ACQUISITION_COST_UTIL260621.md",
      "docs/MVP_REVERSE_FILTER_DTO260621.md",
      "docs/MVP_CORE_UNIT_TESTS260621.md",
    ],
    implLocation: "frontend/lib/acquisitionCostCore.ts; frontend/lib/reverseFilterDto.ts; frontend/lib/reverseFilterCore.ts",
    demoStrategy: "mock",
    engineering: {
      authGate: "테스트/계산 모듈입니다.",
      clientActions: [],
      serverActions: [],
      dataReads: ["business-rule test fixtures"],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "finance-policy": "금융/예산 계산의 회귀를 단위 테스트로 잠급니다.",
        "data-accuracy": "DTO와 core 계산 계약이 UI/Server Action의 공통 기준입니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "empty-results",
    title: "검색 결과 Empty State",
    route: "/app/results?budgetMin=...&budgetMax=...",
    designSpecType: "system-state",
    flowNote: "매칭 결과가 없을 때 다음 행동을 안내하는 상태입니다.",
    status: "verified",
    workItems: ["mvp-017"],
    requirementRefs: ["docs/MVP_REVERSE_FILTER_EMPTY_STATE260624.md"],
    implLocation: "frontend/app/app/results/page.tsx",
    demoStrategy: "mock",
    engineering: {
      authGate: "공개 상태입니다.",
      clientActions: ["예산 다시 입력", "필터 초기화"],
      serverActions: ["reverseFilterAction"],
      dataReads: ["reverse filter result groups"],
      dataWrites: [],
      telemetryEvents: ["reverse_filter_empty_viewed 예정"],
      exceptionStates: [],
      controlAreaNotes: {
        "ux-safety": "0건 결과에서 막다른 길이 아니라 다음 행동을 제공합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "data-disclosure",
    title: "데이터 기준일 및 면책 고지",
    route: "공통 데이터 화면",
    designSpecType: "system-state",
    flowNote: "데이터 기반 화면에서 기준일/원천/투자 판단 면책을 고정 노출합니다.",
    status: "verified",
    workItems: ["mvp-018"],
    requirementRefs: ["docs/MVP_DATA_DISCLOSURE_NOTICE260624.md"],
    implLocation: "frontend/components/domain/DataDisclosureNotice.tsx; frontend/lib/dataDisclosure.ts",
    demoStrategy: "mock",
    engineering: {
      authGate: "공개 상태입니다.",
      clientActions: [],
      serverActions: [],
      dataReads: ["MVP_DATA_DISCLOSURE"],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "data-accuracy": "데이터 화면의 기준일과 원천 데이터 기준을 명확히 합니다.",
        "ux-safety": "투자 판단 책임과 실제 거래 확인 필요성을 고정 고지합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "preview-environment",
    title: "Preview 배포 환경",
    route: "Vercel Preview",
    designSpecType: "system-state",
    flowNote: "Production 영향 없이 MVP 기능을 검증하는 Preview 환경 상태입니다.",
    status: "verified",
    workItems: ["mvp-025"],
    requirementRefs: ["docs/MVP_PREVIEW_WORKFLOW260621.md", "docs/MVP_PREVIEW_ENVIRONMENT260627.md"],
    implLocation: "frontend/app/app/preview-health/page.tsx; frontend/app/api/preview-health/route.ts",
    demoStrategy: "mock",
    engineering: {
      authGate: "Preview 공유 URL은 플래그와 환경변수로 제어합니다.",
      clientActions: [],
      serverActions: [],
      dataReads: ["Vercel env vars", "Preview Supabase env vars"],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: [],
      controlAreaNotes: {
        "preview-deploy": "Preview와 Production의 Supabase 환경변수 분리 및 health check 표면을 구성했습니다.",
        "security-access": "Preview health는 비밀값을 노출하지 않는 점검 표면으로 유지합니다.",
      },
    },
  },
  {
    plane: "system",
    slug: "mvp-release-readiness",
    title: "MVP 릴리즈 판단 상태",
    route: "GitHub Project #3 Sprint 5",
    designSpecType: "system-state",
    flowNote: "Production 병합 전 smoke, 에러/로딩, 접근성, 문서 정리, 릴리즈 판단 자료를 추적합니다.",
    status: "partial",
    statusNote: "MVP-026~028은 완료됐고 MVP-029~030 문서 정리/릴리즈 판단은 후속입니다.",
    workItems: ["mvp-026", "mvp-027", "mvp-028", "mvp-029", "mvp-030"],
    requirementRefs: [
      "docs/MVP_PRODUCTION_SMOKE_TEST_CHECKLIST260627.md",
      "docs/MVP_ERROR_LOADING_STATES260627.md",
      "docs/MVP_BASIC_ACCESSIBILITY260627.md",
    ],
    demoStrategy: "mock",
    engineering: {
      authGate: "릴리즈 검증 상태입니다.",
      clientActions: ["Smoke checklist 검토", "접근성/에러 상태 점검"],
      serverActions: [],
      dataReads: ["GitHub Project #3", "Vercel Preview checks", "E2E smoke results"],
      dataWrites: [],
      telemetryEvents: [],
      exceptionStates: ["empty-results", "data-disclosure"],
      controlAreaNotes: {
        "preview-deploy": "Production 병합 전 Preview smoke와 환경 분리를 확인합니다.",
        "ux-safety": "기본 접근성, 에러 처리, 로딩 상태를 릴리즈 판단 전에 확인합니다.",
        observability: "릴리즈 판단 자료는 테스트/체크 결과를 근거로 합니다.",
      },
    },
  },
] satisfies PlayBoardScreen[];

export const playBoardWorkItems = [
  {
    id: "mvp-001",
    title: "신규 GitHub Project 생성 및 필드 정의",
    phase: "Sprint 0 · Foundation",
    status: "done",
    externalRefs: ["#96", "MVP-001"],
    dependsOn: [],
    screens: ["system/mvp-project-foundation"],
    doc: "docs/MVP_PREVIEW_WORKFLOW260621.md",
  },
  {
    id: "mvp-002",
    title: "MVP 브랜치 및 Vercel Preview 운영 규칙 정리",
    phase: "Sprint 0 · Foundation",
    status: "done",
    externalRefs: ["#97", "MVP-002"],
    dependsOn: ["mvp-001"],
    screens: ["system/mvp-project-foundation", "system/preview-environment"],
    doc: "docs/MVP_PREVIEW_WORKFLOW260621.md",
  },
  {
    id: "mvp-003",
    title: "MVP 데이터 컬럼 표준 정의",
    phase: "Sprint 0 · Foundation",
    status: "done",
    externalRefs: ["#98", "MVP-003"],
    dependsOn: ["mvp-002"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_DATA_COLUMN_CONTRACT260621.md",
  },
  {
    id: "mvp-004",
    title: "Supabase MVP 스키마 설계",
    phase: "Sprint 1 · Core Data",
    status: "done",
    externalRefs: ["#99", "MVP-004"],
    dependsOn: ["mvp-003"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_SUPABASE_SCHEMA260621.md",
  },
  {
    id: "mvp-005",
    title: "구역 CSV 정규화 스크립트 작성",
    phase: "Sprint 1 · Core Data",
    status: "done",
    externalRefs: ["#100", "MVP-005"],
    dependsOn: ["mvp-003"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_GOLDEN_SAMPLES_NORMALIZATION260621.md",
  },
  {
    id: "mvp-006",
    title: "Naver Land XLSX 정규화 스크립트 작성",
    phase: "Sprint 1 · Core Data",
    status: "done",
    externalRefs: ["#101", "MVP-006"],
    dependsOn: ["mvp-003"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_NAVER_LAND_NORMALIZATION260621.md",
  },
  {
    id: "mvp-007",
    title: "Supabase seed/upsert 스크립트 작성",
    phase: "Sprint 1 · Core Data",
    status: "done",
    externalRefs: ["#102", "MVP-007"],
    dependsOn: ["mvp-004", "mvp-005", "mvp-006"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_SUPABASE_SEED_UPSERT260621.md",
  },
  {
    id: "mvp-008",
    title: "데이터 품질 검증 리포트 작성",
    phase: "Sprint 1 · Core Data",
    status: "done",
    externalRefs: ["#103", "MVP-008"],
    dependsOn: ["mvp-007"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/MVP_DATA_QUALITY_REPORT260621.md",
  },
  {
    id: "mvp-009",
    title: "LTV 정책 조회 유틸",
    phase: "Sprint 2 · Core Features",
    status: "done",
    externalRefs: ["#104", "MVP-009"],
    dependsOn: ["mvp-004"],
    screens: ["ops/ltv-policy"],
    doc: "docs/MVP_LTV_POLICY_UTIL260621.md",
  },
  {
    id: "mvp-010",
    title: "취득세 및 비용 계산 유틸",
    phase: "Sprint 2 · Core Features",
    status: "done",
    externalRefs: ["#105", "MVP-010"],
    dependsOn: ["mvp-003"],
    screens: ["system/core-calculation-tests"],
    doc: "docs/MVP_ACQUISITION_COST_UTIL260621.md",
  },
  {
    id: "mvp-011",
    title: "Reverse Filter DTO 및 Zod 스키마 정의",
    phase: "Sprint 2 · Core Features",
    status: "done",
    externalRefs: ["#106", "MVP-011"],
    dependsOn: ["mvp-010"],
    screens: ["system/core-calculation-tests"],
    doc: "docs/MVP_REVERSE_FILTER_DTO260621.md",
  },
  {
    id: "mvp-012",
    title: "Reverse Filter Server Action",
    phase: "Sprint 2 · Core Features",
    status: "done",
    externalRefs: ["#107", "MVP-012"],
    dependsOn: ["mvp-009", "mvp-011"],
    screens: ["b2c/reverse-filter-results", "ops/ltv-policy"],
    doc: "docs/MVP_REVERSE_FILTER_ACTION260621.md",
  },
  {
    id: "mvp-013",
    title: "핵심 계산 단위 테스트 작성",
    phase: "Sprint 2 · Core Features",
    status: "done",
    externalRefs: ["#108", "MVP-013"],
    dependsOn: ["mvp-010", "mvp-011", "mvp-012"],
    screens: ["system/core-calculation-tests"],
    doc: "docs/MVP_CORE_UNIT_TESTS260621.md",
  },
  {
    id: "mvp-014",
    title: "B2C 단일 입력 랜딩 구현",
    phase: "Sprint 3 · B2C Flow",
    status: "done",
    externalRefs: ["#109", "MVP-014"],
    dependsOn: ["mvp-011"],
    screens: ["b2c/landing-budget-search"],
    doc: "docs/MVP_BUDGET_RANGE_LANDING260621.md",
  },
  {
    id: "mvp-015",
    title: "Reverse Filter 결과 리스트",
    phase: "Sprint 3 · B2C Flow",
    status: "done",
    externalRefs: ["#110", "MVP-015"],
    dependsOn: ["mvp-012", "mvp-014"],
    screens: ["b2c/reverse-filter-results"],
    doc: "docs/MVP_REVERSE_FILTER_RESULTS260623.md",
  },
  {
    id: "mvp-016",
    title: "결과 정렬 및 필터 UI 구현",
    phase: "Sprint 3 · B2C Flow",
    status: "done",
    externalRefs: ["#111", "MVP-016"],
    dependsOn: ["mvp-015"],
    screens: ["b2c/reverse-filter-results"],
    doc: "docs/MVP_REVERSE_FILTER_RESULTS_FILTERS260623.md",
  },
  {
    id: "mvp-017",
    title: "매칭 0건 Empty State 구현",
    phase: "Sprint 3 · B2C Flow",
    status: "done",
    externalRefs: ["#112", "MVP-017"],
    dependsOn: ["mvp-015"],
    screens: ["system/empty-results"],
    doc: "docs/MVP_REVERSE_FILTER_EMPTY_STATE260624.md",
  },
  {
    id: "mvp-018",
    title: "데이터 기준일 및 면책 문구 고정 노출",
    phase: "Sprint 3 · B2C Flow",
    status: "done",
    externalRefs: ["#113", "MVP-018"],
    dependsOn: ["mvp-015"],
    screens: ["system/data-disclosure"],
    doc: "docs/MVP_DATA_DISCLOSURE_NOTICE260624.md",
  },
  {
    id: "mvp-019",
    title: "구역 상세 Lite 화면 구현",
    phase: "Sprint 4 · Comparison",
    status: "done",
    externalRefs: ["#114", "MVP-019"],
    dependsOn: ["mvp-015"],
    screens: ["b2c/zone-detail-lite"],
    doc: "docs/MVP_ZONE_DETAIL_LITE260624.md",
  },
  {
    id: "mvp-020",
    title: "기축 레퍼런스 카드 구현",
    phase: "Sprint 4 · Comparison",
    status: "done",
    externalRefs: ["#115", "MVP-020"],
    dependsOn: ["mvp-019"],
    screens: ["b2c/zone-detail-lite"],
    doc: "docs/MVP_REFERENCE_APARTMENT_CARD260624.md",
  },
  {
    id: "mvp-021",
    title: "비교 데이터 생성 Server Action 구현",
    phase: "Sprint 4 · Comparison",
    status: "done",
    externalRefs: ["#116", "MVP-021"],
    dependsOn: ["mvp-019", "mvp-020"],
    screens: ["b2c/comparison-assets"],
    doc: "docs/MVP_COMPARISON_DATA_ACTION260624.md",
  },
  {
    id: "mvp-022",
    title: "간단 리포트 섹션 구현",
    phase: "Sprint 4 · Comparison",
    status: "done",
    externalRefs: ["#117", "MVP-022"],
    dependsOn: ["mvp-021"],
    screens: ["b2c/comparison-assets"],
    doc: "docs/MVP_SIMPLE_REPORT_SECTION260625.md",
  },
  {
    id: "mvp-023",
    title: "사업 단계/실투자금 시각화 구현",
    phase: "Sprint 4 · Comparison",
    status: "done",
    externalRefs: ["#118", "MVP-023"],
    dependsOn: ["mvp-016"],
    screens: ["b2c/reverse-filter-results", "b2c/stage-cash-scatter"],
    doc: "docs/MVP_STAGE_CASH_VISUALIZATION260626.md",
  },
  {
    id: "mvp-024",
    title: "B2C 핵심 플로우 E2E 작성",
    phase: "Sprint 5 · QA & Deploy",
    status: "done",
    externalRefs: ["#119", "MVP-024"],
    dependsOn: ["mvp-022", "mvp-023"],
    screens: [
      "b2c/landing-budget-search",
      "b2c/reverse-filter-results",
      "b2c/zone-detail-lite",
      "b2c/comparison-assets",
    ],
    doc: "docs/MVP_B2C_CORE_FLOW_E2E260626.md",
  },
  {
    id: "mvp-025",
    title: "Preview 배포 환경 구성",
    phase: "Sprint 5 · QA & Deploy",
    status: "done",
    externalRefs: ["#120", "MVP-025"],
    dependsOn: ["mvp-024"],
    screens: ["system/preview-environment"],
    doc: "docs/MVP_PREVIEW_ENVIRONMENT260627.md",
  },
  {
    id: "mvp-026",
    title: "Production 병합 전 Smoke Test 체크리스트 작성",
    phase: "Sprint 5 · QA & Deploy",
    status: "done",
    externalRefs: ["#121", "MVP-026"],
    dependsOn: ["mvp-024", "mvp-025"],
    screens: ["system/mvp-release-readiness"],
    doc: "docs/MVP_PRODUCTION_SMOKE_TEST_CHECKLIST260627.md",
  },
  {
    id: "mvp-027",
    title: "기본 에러 처리 및 로딩 상태 구현",
    phase: "Sprint 5 · QA & Deploy",
    status: "done",
    externalRefs: ["#122", "MVP-027"],
    dependsOn: ["mvp-024"],
    screens: ["system/mvp-release-readiness"],
    doc: "docs/MVP_ERROR_LOADING_STATES260627.md",
  },
  {
    id: "mvp-028",
    title: "기본 접근성 점검",
    phase: "Sprint 5 · QA & Deploy",
    status: "done",
    externalRefs: ["#123", "MVP-028"],
    dependsOn: ["mvp-024"],
    screens: ["system/mvp-release-readiness"],
    doc: "docs/MVP_BASIC_ACCESSIBILITY260627.md",
  },
  {
    id: "mvp-029",
    title: "문서 정리 및 원본 이슈 참조 정리",
    phase: "Sprint 5 · QA & Deploy",
    status: "not_started",
    externalRefs: ["#124", "MVP-029"],
    dependsOn: ["mvp-025", "mvp-026"],
    screens: ["system/mvp-release-readiness"],
    doc: "docs/MVP_PREVIEW_WORKFLOW260621.md",
  },
  {
    id: "mvp-030",
    title: "MVP 릴리즈 판단 회의 자료 작성",
    phase: "Sprint 5 · QA & Deploy",
    status: "not_started",
    externalRefs: ["#125", "MVP-030"],
    dependsOn: ["mvp-026", "mvp-029"],
    screens: ["system/mvp-release-readiness"],
    doc: "docs/MVP_PREVIEW_WORKFLOW260621.md",
  },
  {
    id: "mvp-data-141",
    title: "최신 파일 세트 RULE 및 LTV 기축 대조군 데이터 파이프라인 정리",
    phase: "MVP Data Follow-up",
    status: "not_started",
    externalRefs: ["#141"],
    dependsOn: ["mvp-021"],
    screens: ["system/mvp-data-pipeline"],
    doc: "docs/DATA_MANAGEMENT_PLAN.md",
  },
] satisfies PlayBoardWorkItem[];

export const playBoardControlAreas = [
  {
    id: "data-accuracy",
    title: "데이터 정확성",
    goal: "구역, 투자금, 기축 기준가의 출처와 갱신 기준을 추적 가능하게 유지합니다.",
    summary: "SeedFit의 핵심 신뢰는 큐레이션 데이터 기준일, 원천 파일, DB 반영 상태가 화면과 함께 움직이는 데 있습니다.",
    policies: [
      {
        statement: "모든 금액은 원 단위 integer KRW를 기준으로 저장·계산합니다.",
        detail: "원천 파일의 억 표현은 import/normalization 단계에서만 허용합니다.",
      },
      {
        statement: "데이터 화면은 기준일과 면책 고지를 함께 노출합니다.",
        detail: "사용자는 투자 판단 전에 원천 데이터 기준과 실제 거래 확인 필요성을 볼 수 있어야 합니다.",
      },
    ],
    decisions: [{ name: "Zone tier storage", value: "티어는 저장하지 않고 예산 기준 runtime matching으로 계산" }],
    standards: [
      { title: "MVP Data Disclosure", path: "docs/MVP_DATA_DISCLOSURE_NOTICE260624.md" },
      { title: "Data Management Plan", path: "docs/DATA_MANAGEMENT_PLAN.md" },
    ],
    workItems: ["mvp-018", "mvp-021"],
    gaps: ["Comparison Assets DB 테이블 영속화는 MVP 완료 후 후속 구현으로 남아 있습니다."],
  },
  {
    id: "finance-policy",
    title: "금융 계산/LTV 정책",
    goal: "LTV·취득세·기축 필요 현금 계산을 하드코딩하지 않고 검증 가능한 정책 계약으로 유지합니다.",
    summary: "Reverse Filter와 비교 화면은 금융 가정이 사용자 판단에 직접 영향을 주므로 정책 출처와 모델 선택을 분리해야 합니다.",
    policies: [
      {
        statement: "LTV/DSR 정책값은 하드코딩하지 않습니다.",
        detail: "활성 정책은 DB/운영 표면에서 관리하는 구조를 우선합니다.",
      },
      {
        statement: "기축 대조군 LTV 모델은 생애최초 70%와 일반 40%를 구분합니다.",
        detail: "기본값은 생애최초 70%이며 사용자는 일반 40%를 선택할 수 있습니다.",
      },
    ],
    decisions: [{ name: "Default comparison LTV model", value: "firstHome70" }],
    standards: [
      { title: "LTV Policy Utility", path: "docs/MVP_LTV_POLICY_UTIL260621.md" },
      { title: "Comparison Data Action", path: "docs/MVP_COMPARISON_DATA_ACTION260624.md" },
    ],
    workItems: ["mvp-009", "mvp-012", "mvp-021"],
    gaps: ["검증된 LTV/DSR 정책 출처가 없는 구간의 ratio 값은 비워둡니다."],
  },
  {
    id: "security-access",
    title: "보안/접근제어",
    goal: "B2B·Admin·민감 데이터 화면은 RBAC와 서버 전용 비밀값 원칙을 지킵니다.",
    summary: "MVP B2C 화면은 공개 중심이지만 Admin/B2B 확장 시 민감 정보 보호가 핵심 제어 영역입니다.",
    policies: [
      {
        statement: "서비스 role key와 운영 비밀값은 서버 전용으로 유지합니다.",
        detail: "NEXT_PUBLIC 변수에는 공개 가능한 값만 넣습니다.",
      },
      {
        statement: "Admin/B2B 화면은 후속 구현에서 권한 게이트를 적용합니다.",
        detail: "현재 partial 화면은 PlayBoard에 갭으로 표시하고 완료로 선언하지 않습니다.",
      },
    ],
    decisions: [{ name: "Current MVP auth posture", value: "3 Month MVP는 B2C/Preview 검증 중심, Admin/B2B는 full-spec 후속" }],
    standards: [{ title: "Project Security Rules", path: "AGENTS.md" }],
    workItems: ["mvp-025", "mvp-027"],
    gaps: ["Admin/B2B RBAC는 3 Month MVP PlayBoard의 tracked implementation 범위 밖이며 full-spec 후속입니다."],
  },
  {
    id: "preview-deploy",
    title: "Preview/배포 분리",
    goal: "MVP 검증을 Production 영향 없이 Preview에서 수행합니다.",
    summary: "Preview와 Production의 DB/env가 섞이지 않아야 MVP 데이터를 안전하게 검증할 수 있습니다.",
    policies: [
      {
        statement: "Production 설정은 issue branch에서 변경하지 않습니다.",
        detail: "MVP 기능 검증은 Preview URL에서 수행합니다.",
      },
      {
        statement: "PlayBoard는 production 기본 비공개입니다.",
        detail: "로컬은 자동 노출, preview/production은 PLAYBOARD_ENABLED 플래그가 필요합니다.",
      },
    ],
    decisions: [{ name: "PlayBoard route", value: "/app/playboard" }],
    standards: [{ title: "MVP Preview Workflow", path: "docs/MVP_PREVIEW_WORKFLOW260621.md" }],
    workItems: ["mvp-002", "mvp-024", "mvp-025", "mvp-026", "mvp-029", "mvp-030"],
    gaps: ["Vercel Preview 환경변수와 MVP Supabase 분리 검증은 MVP-025에서 완료해야 합니다."],
  },
  {
    id: "performance",
    title: "성능",
    goal: "Reverse Filter, 랜딩, 리포트 렌더가 SRS 목표를 만족하도록 추적합니다.",
    summary: "SeedFit의 사용자 가치는 짧은 탐색 시간에 있으므로 p95와 렌더 성능을 화면별 계약에 묶습니다.",
    policies: [
      {
        statement: "Reverse Filter Server Action p95 목표는 1.5초 이하입니다.",
        detail: "부하 목표는 SRS 기준이며 MVP에서는 회귀 감시 항목으로 유지합니다.",
      },
      {
        statement: "Landing LCP 목표는 1.0초 이하입니다.",
        detail: "랜딩 화면 변경은 LCP에 미치는 영향을 고려합니다.",
      },
    ],
    decisions: [{ name: "MVP performance evidence", value: "build + targeted tests first, load test later" }],
    standards: [{ title: "SRS Performance Standards", path: "docs/01_SRS-001_v1.2.md" }],
    workItems: ["mvp-012", "mvp-014"],
    gaps: ["p95 부하 테스트 자동화는 아직 PlayBoard 검증 루틴에 포함되지 않았습니다."],
  },
  {
    id: "observability",
    title: "관측/분석",
    goal: "검색 완료율, 비교 진입, LTV 모델 선택 등 MVP KPI를 계측 가능한 계약으로 둡니다.",
    summary: "현재 Vercel Analytics와 Speed Insights는 연결되어 있고, 제품 이벤트 명세는 후속 확정이 필요합니다.",
    policies: [
      {
        statement: "North Star KPI는 가용 현금 쿼리 검색 완료율입니다.",
        detail: "Amplitude funnel 기준 65% 이상이 목표입니다.",
      },
    ],
    decisions: [{ name: "Current analytics package", value: "Vercel Analytics + Speed Insights installed" }],
    standards: [{ title: "PRD Success Metrics", path: "docs/00_PRD_v0.1.md" }],
    workItems: ["mvp-024", "mvp-026", "mvp-030"],
    gaps: ["Amplitude event taxonomy는 화면별 telemetryEvents와 동기화해야 합니다."],
  },
  {
    id: "ux-safety",
    title: "UX 안전/면책",
    goal: "사용자가 금융 가정, 데이터 한계, 다음 행동을 오해하지 않도록 보호합니다.",
    summary: "예산 범위, 기축 레퍼런스, 기축 대조군, Empty State의 문구가 사용자 판단의 안전장치입니다.",
    policies: [
      {
        statement: "기축 레퍼런스와 같은 예산 기축 대조군은 분리된 개념입니다.",
        detail: "구역 상세은 미래가치 레퍼런스, 비교 화면은 같은 실투자금 대조군입니다.",
      },
      {
        statement: "0건 결과는 다음 행동을 제시합니다.",
        detail: "예산/필터 조정 없이 막다른 길로 끝내지 않습니다.",
      },
    ],
    decisions: [{ name: "Budget input contract", value: "budgetMinKrw/budgetMaxKrw range-first" }],
    standards: [
      { title: "Budget Range Landing", path: "docs/MVP_BUDGET_RANGE_LANDING260621.md" },
      { title: "Reference Apartment Card", path: "docs/MVP_REFERENCE_APARTMENT_CARD260624.md" },
    ],
    workItems: ["mvp-014", "mvp-017", "mvp-020", "mvp-022", "mvp-027", "mvp-028"],
    gaps: ["투자 판단 면책 문구의 화면별 위치와 반복 강도는 사용자 테스트 후 조정합니다."],
  },
] satisfies PlayBoardControlArea[];

export const playBoardFlows = [
  {
    id: "b2c-core",
    plane: "b2c",
    title: "B2C 핵심 투자자 흐름",
    description: "예산 입력에서 결과, 구역 상세, 같은 실투자금 기축단지 비교까지 이어지는 MVP 핵심 흐름입니다.",
    kind: "sequence",
    screens: [
      "b2c/landing-budget-search",
      "b2c/reverse-filter-results",
      "b2c/zone-detail-lite",
      "b2c/comparison-assets",
    ],
  },
  {
    id: "ops-governance",
    plane: "ops",
    title: "운영 정책 관리 흐름",
    description: "LTV 정책과 Preview 배포 검증을 통해 MVP 운영 안전성을 관리합니다.",
    kind: "sequence",
    screens: ["ops/ltv-policy"],
  },
  {
    id: "system-states",
    plane: "system",
    title: "시스템 상태 케이스",
    description: "Empty State, 데이터 고지, Preview 환경 같은 독립 상태 케이스입니다.",
    kind: "case-set",
    screens: [
      "system/mvp-project-foundation",
      "system/mvp-data-pipeline",
      "system/core-calculation-tests",
      "system/empty-results",
      "system/data-disclosure",
      "system/preview-environment",
      "system/mvp-release-readiness",
    ],
  },
] satisfies PlayBoardFlow[];

