export const scatterData = [
  {
    "id": "미아 2구역",
    "name": "미아 2구역",
    "district": "강북구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 6.2,
    "investmentMax": 10.5
  },
  {
    "id": "미아 3구역",
    "name": "미아 3구역",
    "district": "강북구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 12.0,
    "investmentMax": 12.0
  },
  {
    "id": "미아 4구역",
    "name": "미아 4구역",
    "district": "강북구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 11.2,
    "investmentMax": 16.0
  },
  {
    "id": "미아 9-2구역(재건축)",
    "name": "미아 9-2구역(재건축)",
    "district": "강북구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 5.4,
    "investmentMax": 10.0
  },
  {
    "id": "구의1동 221-1",
    "name": "구의1동 221-1",
    "district": "광진구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 4.0,
    "investmentMax": 5.0
  },
  {
    "id": "구의동 32",
    "name": "구의동 32",
    "district": "광진구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 6.0,
    "investmentMax": 6.0
  },
  {
    "id": "구의동 46",
    "name": "구의동 46",
    "district": "광진구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 3.3,
    "investmentMax": 4.3
  },
  {
    "id": "자양 7구역",
    "name": "자양 7구역",
    "district": "광진구",
    "tier": "T4",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 16.1,
    "investmentMax": 17.9
  },
  {
    "id": "자양1동 593(A)(모아타운)",
    "name": "자양1동 593(A)(모아타운)",
    "district": "광진구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "(모아)대상지 선정",
    "coverage": "SUB",
    "investmentMin": 6.3,
    "investmentMax": 7.5
  },
  {
    "id": "자양1동 779(모아타운)",
    "name": "자양1동 779(모아타운)",
    "district": "광진구",
    "tier": "T2",
    "stage": 2.1,
    "stageStr": "(모아)관리계획고시",
    "coverage": "CORE",
    "investmentMin": 4.3,
    "investmentMax": 4.8
  },
  {
    "id": "자양2동 649(B)(모아타운)",
    "name": "자양2동 649(B)(모아타운)",
    "district": "광진구",
    "tier": "T3",
    "stage": 2.1,
    "stageStr": "(모아)관리계획고시",
    "coverage": "CORE",
    "investmentMin": 6.9,
    "investmentMax": 7.8
  },
  {
    "id": "자양2동 663(C)(모아타운)",
    "name": "자양2동 663(C)(모아타운)",
    "district": "광진구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "(모아)대상지 선정",
    "coverage": "SUB",
    "investmentMin": 5.2,
    "investmentMax": 6.8
  },
  {
    "id": "자양2동 681(모아타운)",
    "name": "자양2동 681(모아타운)",
    "district": "광진구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "대상지철회",
    "coverage": "SUB",
    "investmentMin": 3.9,
    "investmentMax": 7.4
  },
  {
    "id": "자양4동 A구역",
    "name": "자양4동 A구역",
    "district": "광진구",
    "tier": "T4",
    "stage": 2.1,
    "stageStr": "정비구역 지정",
    "coverage": "CORE",
    "investmentMin": 15.8,
    "investmentMax": 18.0
  },
  {
    "id": "자양동 227-147",
    "name": "자양동 227-147",
    "district": "광진구",
    "tier": "T3",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 9.0,
    "investmentMax": 10.25
  },
  {
    "id": "자양동 629(모아타운)",
    "name": "자양동 629(모아타운)",
    "district": "광진구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "추진준비",
    "coverage": "SUB",
    "investmentMin": 3.4,
    "investmentMax": 4.15
  },
  {
    "id": "자양동 772-1(건대모아)",
    "name": "자양동 772-1(건대모아)",
    "district": "광진구",
    "tier": "T2",
    "stage": 2.1,
    "stageStr": "(모아)관리계획고시",
    "coverage": "CORE",
    "investmentMin": 4.7,
    "investmentMax": 5.1
  },
  {
    "id": "중곡 1구역(A5)",
    "name": "중곡 1구역(A5)",
    "district": "광진구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 완료",
    "coverage": "SUB",
    "investmentMin": 5.99,
    "investmentMax": 5.99
  },
  {
    "id": "중곡동 232-1(A4)",
    "name": "중곡동 232-1(A4)",
    "district": "광진구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 2.0,
    "investmentMax": 2.5
  },
  {
    "id": "수택 2구역",
    "name": "수택 2구역",
    "district": "구리시",
    "tier": "T1",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 2.4,
    "investmentMax": 2.9
  },
  {
    "id": "독산 1구역",
    "name": "독산 1구역",
    "district": "금천구",
    "tier": "T3",
    "stage": 3.0,
    "stageStr": "사업시행자 지정",
    "coverage": "CORE",
    "investmentMin": 6.9,
    "investmentMax": 11.8
  },
  {
    "id": "독산 2구역",
    "name": "독산 2구역",
    "district": "금천구",
    "tier": "T2",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 4.8,
    "investmentMax": 8.8
  },
  {
    "id": "독산시흥구역",
    "name": "독산시흥구역",
    "district": "금천구",
    "tier": "T2",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 3.35,
    "investmentMax": 9.3
  },
  {
    "id": "용두 7구역",
    "name": "용두 7구역",
    "district": "동대문구",
    "tier": "T2",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 3.15,
    "investmentMax": 3.8
  },
  {
    "id": "이문 4구역",
    "name": "이문 4구역",
    "district": "동대문구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 13.0,
    "investmentMax": 14.5
  },
  {
    "id": "전농 10구역",
    "name": "전농 10구역",
    "district": "동대문구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 2.3,
    "investmentMax": 3.6
  },
  {
    "id": "전농 15구역",
    "name": "전농 15구역",
    "district": "동대문구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 1.8,
    "investmentMax": 2.0
  },
  {
    "id": "전농 8구역",
    "name": "전농 8구역",
    "district": "동대문구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 9.5,
    "investmentMax": 12.55
  },
  {
    "id": "제기 6구역",
    "name": "제기 6구역",
    "district": "동대문구",
    "tier": "T3",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 9.8,
    "investmentMax": 9.8
  },
  {
    "id": "청량리 8구역",
    "name": "청량리 8구역",
    "district": "동대문구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 12.0,
    "investmentMax": 12.0
  },
  {
    "id": "노량진 1구역",
    "name": "노량진 1구역",
    "district": "동작구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 15.8,
    "investmentMax": 27.0
  },
  {
    "id": "노량진 3구역",
    "name": "노량진 3구역",
    "district": "동작구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 20.0,
    "investmentMax": 33.0
  },
  {
    "id": "노량진 7구역",
    "name": "노량진 7구역",
    "district": "동작구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 21.0,
    "investmentMax": 31.0
  },
  {
    "id": "사당 12구역",
    "name": "사당 12구역",
    "district": "동작구",
    "tier": "T1",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 1.55,
    "investmentMax": 4.1
  },
  {
    "id": "사당 15구역",
    "name": "사당 15구역",
    "district": "동작구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 5.5,
    "investmentMax": 6.4
  },
  {
    "id": "사당 16구역",
    "name": "사당 16구역",
    "district": "동작구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 5.4,
    "investmentMax": 5.4
  },
  {
    "id": "사당 17구역",
    "name": "사당 17구역",
    "district": "동작구",
    "tier": "T4",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 10.0,
    "investmentMax": 13.5
  },
  {
    "id": "사당 18구역",
    "name": "사당 18구역",
    "district": "동작구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 2.8,
    "investmentMax": 3.1
  },
  {
    "id": "사당 21구역",
    "name": "사당 21구역",
    "district": "동작구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 3.7,
    "investmentMax": 6.5
  },
  {
    "id": "사당 5구역(재건축)",
    "name": "사당 5구역(재건축)",
    "district": "동작구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 7.5,
    "investmentMax": 12.0
  },
  {
    "id": "상도 14구역",
    "name": "상도 14구역",
    "district": "동작구",
    "tier": "T3",
    "stage": 3.0,
    "stageStr": "사업시행자 지정",
    "coverage": "CORE",
    "investmentMin": 6.8,
    "investmentMax": 8.6
  },
  {
    "id": "상도 15구역",
    "name": "상도 15구역",
    "district": "동작구",
    "tier": "T3",
    "stage": 4.1,
    "stageStr": "시공사 선정",
    "coverage": "CORE",
    "investmentMin": 8.0,
    "investmentMax": 9.6
  },
  {
    "id": "상도 16구역",
    "name": "상도 16구역",
    "district": "동작구",
    "tier": "T2",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 3.9,
    "investmentMax": 4.0
  },
  {
    "id": "상도 21구역(모아타운)",
    "name": "상도 21구역(모아타운)",
    "district": "동작구",
    "tier": "T1",
    "stage": 2.1,
    "stageStr": "(모아)관리계획고시",
    "coverage": "CORE",
    "investmentMin": 1.8,
    "investmentMax": 3.9
  },
  {
    "id": "상도 23구역",
    "name": "상도 23구역",
    "district": "동작구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 4.85,
    "investmentMax": 5.0
  },
  {
    "id": "상도 25구역",
    "name": "상도 25구역",
    "district": "동작구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 3.2,
    "investmentMax": 4.15
  },
  {
    "id": "흑석 10구역",
    "name": "흑석 10구역",
    "district": "동작구",
    "tier": "T3",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 7.0,
    "investmentMax": 7.0
  },
  {
    "id": "공덕 7구역",
    "name": "공덕 7구역",
    "district": "마포구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 9.48,
    "investmentMax": 11.5
  },
  {
    "id": "공덕 8구역",
    "name": "공덕 8구역",
    "district": "마포구",
    "tier": "T3",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 7.62,
    "investmentMax": 8.2
  },
  {
    "id": "대흥 5구역",
    "name": "대흥 5구역",
    "district": "마포구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 4.9,
    "investmentMax": 5.2
  },
  {
    "id": "신수 13구역",
    "name": "신수 13구역",
    "district": "마포구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 6.0,
    "investmentMax": 6.2
  },
  {
    "id": "염리 4구역",
    "name": "염리 4구역",
    "district": "마포구",
    "tier": "T4",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 10.65,
    "investmentMax": 23.5
  },
  {
    "id": "염리 5구역",
    "name": "염리 5구역",
    "district": "마포구",
    "tier": "T3",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 7.8,
    "investmentMax": 24.85
  },
  {
    "id": "북아현 2구역",
    "name": "북아현 2구역",
    "district": "서대문구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 16.86,
    "investmentMax": 19.0
  },
  {
    "id": "북아현 3구역",
    "name": "북아현 3구역",
    "district": "서대문구",
    "tier": "T4",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 10.5,
    "investmentMax": 13.61
  },
  {
    "id": "방배 13구역",
    "name": "방배 13구역",
    "district": "서초구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 11.7,
    "investmentMax": 23.0
  },
  {
    "id": "방배 15구역(재건축)",
    "name": "방배 15구역(재건축)",
    "district": "서초구",
    "tier": "T4",
    "stage": 4.1,
    "stageStr": "건축심의",
    "coverage": "CORE",
    "investmentMin": 25.0,
    "investmentMax": 34.0
  },
  {
    "id": "수진 1구역",
    "name": "수진 1구역",
    "district": "성남시 수정구",
    "tier": "T3",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 6.9,
    "investmentMax": 7.58
  },
  {
    "id": "신흥 1구역",
    "name": "신흥 1구역",
    "district": "성남시 수정구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 7.0,
    "investmentMax": 7.6
  },
  {
    "id": "신흥 3구역",
    "name": "신흥 3구역",
    "district": "성남시 수정구",
    "tier": "T3",
    "stage": 4.1,
    "stageStr": "시공사 선정",
    "coverage": "CORE",
    "investmentMin": 5.6,
    "investmentMax": 7.3
  },
  {
    "id": "금호 16구역",
    "name": "금호 16구역",
    "district": "성동구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 14.5,
    "investmentMax": 16.0
  },
  {
    "id": "금호 21구역",
    "name": "금호 21구역",
    "district": "성동구",
    "tier": "T4",
    "stage": 4.1,
    "stageStr": "시공사 선정",
    "coverage": "CORE",
    "investmentMin": 11.8,
    "investmentMax": 16.4
  },
  {
    "id": "금호 22구역",
    "name": "금호 22구역",
    "district": "성동구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 2.5,
    "investmentMax": 3.5
  },
  {
    "id": "금호 23구역",
    "name": "금호 23구역",
    "district": "성동구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 6.9,
    "investmentMax": 6.9
  },
  {
    "id": "사근동 190-2",
    "name": "사근동 190-2",
    "district": "성동구",
    "tier": "T1",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 2.2,
    "investmentMax": 3.7
  },
  {
    "id": "용답 1구역",
    "name": "용답 1구역",
    "district": "성동구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 3.2,
    "investmentMax": 3.8
  },
  {
    "id": "용답 2구역",
    "name": "용답 2구역",
    "district": "성동구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 4.1,
    "investmentMax": 5.5
  },
  {
    "id": "길음 5구역",
    "name": "길음 5구역",
    "district": "성북구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 5.2,
    "investmentMax": 6.0
  },
  {
    "id": "신길음구역",
    "name": "신길음구역",
    "district": "성북구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 8.5,
    "investmentMax": 8.5
  },
  {
    "id": "장위 13-1구역",
    "name": "장위 13-1구역",
    "district": "성북구",
    "tier": "T1",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 1.6,
    "investmentMax": 2.0
  },
  {
    "id": "장위 13-2구역",
    "name": "장위 13-2구역",
    "district": "성북구",
    "tier": "T1",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 1.8,
    "investmentMax": 2.0
  },
  {
    "id": "장위 14구역",
    "name": "장위 14구역",
    "district": "성북구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 5.5,
    "investmentMax": 5.98
  },
  {
    "id": "장위 15구역",
    "name": "장위 15구역",
    "district": "성북구",
    "tier": "T3",
    "stage": 1.2,
    "stageStr": "(모아)통합심의통과",
    "coverage": "SUB",
    "investmentMin": 5.25,
    "investmentMax": 7.1
  },
  {
    "id": "마천 1구역",
    "name": "마천 1구역",
    "district": "송파구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 9.2,
    "investmentMax": 11.0
  },
  {
    "id": "마천 3구역",
    "name": "마천 3구역",
    "district": "송파구",
    "tier": "T4",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 10.6,
    "investmentMax": 11.5
  },
  {
    "id": "신정 1구역",
    "name": "신정 1구역",
    "district": "양천구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 3.0,
    "investmentMax": 3.5
  },
  {
    "id": "신길 16-2구역",
    "name": "신길 16-2구역",
    "district": "영등포구",
    "tier": "T2",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 3.7,
    "investmentMax": 4.7
  },
  {
    "id": "신길 2구역",
    "name": "신길 2구역",
    "district": "영등포구",
    "tier": "T3",
    "stage": 5.1,
    "stageStr": "사업시행인가",
    "coverage": "CORE",
    "investmentMin": 8.5,
    "investmentMax": 13.87
  },
  {
    "id": "여의대방신길 2구역",
    "name": "여의대방신길 2구역",
    "district": "영등포구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 3.4,
    "investmentMax": 3.8
  },
  {
    "id": "남산 1구역",
    "name": "남산 1구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 6.2,
    "investmentMax": 7.0
  },
  {
    "id": "남산 2구역",
    "name": "남산 2구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 4.5,
    "investmentMax": 5.6
  },
  {
    "id": "남산 3구역",
    "name": "남산 3구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 4.0,
    "investmentMax": 4.3
  },
  {
    "id": "동후암 1구역",
    "name": "동후암 1구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 4.6,
    "investmentMax": 6.3
  },
  {
    "id": "동후암 2구역",
    "name": "동후암 2구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 4.0,
    "investmentMax": 4.0
  },
  {
    "id": "동후암 3구역",
    "name": "동후암 3구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 6.0,
    "investmentMax": 7.2
  },
  {
    "id": "서계통합",
    "name": "서계통합",
    "district": "용산구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 6.0,
    "investmentMax": 9.8
  },
  {
    "id": "용산 1구역",
    "name": "용산 1구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 9.8,
    "investmentMax": 10.0
  },
  {
    "id": "용산 3구역",
    "name": "용산 3구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 6.6,
    "investmentMax": 7.6
  },
  {
    "id": "용산 4구역",
    "name": "용산 4구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 3.8,
    "investmentMax": 4.0
  },
  {
    "id": "원효로3가 1구역",
    "name": "원효로3가 1구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "연번 부여",
    "coverage": "SUB",
    "investmentMin": 6.9,
    "investmentMax": 6.9
  },
  {
    "id": "원효로3가 2-2",
    "name": "원효로3가 2-2",
    "district": "용산구",
    "tier": "T3",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 6.5,
    "investmentMax": 6.5
  },
  {
    "id": "이촌1구역(재건축)",
    "name": "이촌1구역(재건축)",
    "district": "용산구",
    "tier": "T4",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 12.0,
    "investmentMax": 14.2
  },
  {
    "id": "이태원 1구역",
    "name": "이태원 1구역",
    "district": "용산구",
    "tier": "T4",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 10.0,
    "investmentMax": 10.0
  },
  {
    "id": "청파 1구역",
    "name": "청파 1구역",
    "district": "용산구",
    "tier": "T3",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 7.5,
    "investmentMax": 20.0
  },
  {
    "id": "청파 2구역",
    "name": "청파 2구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 3.1,
    "stageStr": "조합설립인가",
    "coverage": "CORE",
    "investmentMin": 3.8,
    "investmentMax": 8.1
  },
  {
    "id": "청파 3구역",
    "name": "청파 3구역",
    "district": "용산구",
    "tier": "T2",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 3.0,
    "investmentMax": 4.8
  },
  {
    "id": "한남 1구역",
    "name": "한남 1구역",
    "district": "용산구",
    "tier": "T4",
    "stage": 1.0,
    "stageStr": "신속통합기획 대상지 선정",
    "coverage": "SUB",
    "investmentMin": 28.0,
    "investmentMax": 30.0
  },
  {
    "id": "후암1구역(재건축)",
    "name": "후암1구역(재건축)",
    "district": "용산구",
    "tier": "T4",
    "stage": 2.2,
    "stageStr": "추진위 승인",
    "coverage": "CORE",
    "investmentMin": 14.5,
    "investmentMax": 75.0
  },
  {
    "id": "갈현 1구역",
    "name": "갈현 1구역",
    "district": "은평구",
    "tier": "T3",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 6.8,
    "investmentMax": 7.06
  },
  {
    "id": "대조 1구역",
    "name": "대조 1구역",
    "district": "은평구",
    "tier": "T4",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 15.85,
    "investmentMax": 16.5
  },
  {
    "id": "불광 5구역",
    "name": "불광 5구역",
    "district": "은평구",
    "tier": "T3",
    "stage": 6.1,
    "stageStr": "관리처분인가",
    "coverage": "CORE",
    "investmentMin": 9.17,
    "investmentMax": 10.52
  },
  {
    "id": "신당 10구역",
    "name": "신당 10구역",
    "district": "중구",
    "tier": "T4",
    "stage": 4.1,
    "stageStr": "시공사 선정",
    "coverage": "CORE",
    "investmentMin": 12.0,
    "investmentMax": 19.0
  },
  {
    "id": "중화 6구역",
    "name": "중화 6구역",
    "district": "중랑구",
    "tier": "T1",
    "stage": 2.1,
    "stageStr": "정비구역지정",
    "coverage": "CORE",
    "investmentMin": 2.0,
    "investmentMax": 9.7
  }
];
