export type ComparisonAssetLtvModel = "firstHome70" | "general40";

export type ComparisonAsset = {
  id: string;
  model: ComparisonAssetLtvModel;
  targetPriceBand: string;
  actualPriceKrw: number;
  apartmentName: string;
  location: string;
  areaLabel: string;
  requiredCashKrw: number;
  maxLoanKrw: number;
  appliedLoanKrw: number;
  peakPriceKrw: number | null;
};

export type MatchedComparisonAsset = ComparisonAsset & {
  cashDeltaKrw: number;
  isWithinBudget: boolean;
};

const EOK = 100_000_000;
const DEFAULT_MAX_SHORTFALL_KRW = 20_000_000;
const DEFAULT_SHORTFALL_RATIO = 0.05;

function eok(value: number) {
  return Math.round(value * EOK);
}

export const COMPARISON_ASSETS: ComparisonAsset[] = [
  {
    id: "firstHome70-sk-bukhansan-city",
    model: "firstHome70",
    targetPriceBand: "7억대",
    actualPriceKrw: eok(7),
    apartmentName: "SK북한산시티",
    location: "서울 강북구",
    areaLabel: "24평",
    requiredCashKrw: eok(2.1),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4.9),
    peakPriceKrw: eok(7.8),
  },
  {
    id: "firstHome70-hagye-jangmi",
    model: "firstHome70",
    targetPriceBand: "7억대",
    actualPriceKrw: eok(7.3),
    apartmentName: "하계장미",
    location: "서울 노원구",
    areaLabel: "21평",
    requiredCashKrw: eok(2.19),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.11),
    peakPriceKrw: eok(7.65),
  },
  {
    id: "firstHome70-jugong-tteuranchae",
    model: "firstHome70",
    targetPriceBand: "8억대",
    actualPriceKrw: eok(8),
    apartmentName: "주공뜨란채",
    location: "경기 광명시",
    areaLabel: "24평",
    requiredCashKrw: eok(2.4),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.6),
    peakPriceKrw: eok(7.75),
  },
  {
    id: "firstHome70-dasan-epyeon-xi",
    model: "firstHome70",
    targetPriceBand: "8억대",
    actualPriceKrw: eok(8.4),
    apartmentName: "다산e편한세상자이",
    location: "경기 남양주",
    areaLabel: "24평",
    requiredCashKrw: eok(2.52),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.88),
    peakPriceKrw: eok(8.9),
  },
  {
    id: "firstHome70-wolgye-dongsin",
    model: "firstHome70",
    targetPriceBand: "9억대",
    actualPriceKrw: eok(8.7),
    apartmentName: "월계동신",
    location: "서울 노원구",
    areaLabel: "28평",
    requiredCashKrw: eok(2.7),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(7.8),
  },
  {
    id: "firstHome70-chowon-daewon",
    model: "firstHome70",
    targetPriceBand: "9억대",
    actualPriceKrw: eok(9.7),
    apartmentName: "초원마을대원",
    location: "경기 안양시",
    areaLabel: "24평",
    requiredCashKrw: eok(3.7),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(8.2),
  },
  {
    id: "firstHome70-imundong-ssangyong",
    model: "firstHome70",
    targetPriceBand: "10억대",
    actualPriceKrw: eok(10),
    apartmentName: "이문동 쌍용",
    location: "서울 동대문구",
    areaLabel: "24평",
    requiredCashKrw: eok(4),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(8.47),
  },
  {
    id: "firstHome70-yeomchang-donga-1",
    model: "firstHome70",
    targetPriceBand: "10억대",
    actualPriceKrw: eok(10.7),
    apartmentName: "염창동아1차",
    location: "서울 강서구",
    areaLabel: "24평",
    requiredCashKrw: eok(4.7),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(8.6),
  },
  {
    id: "firstHome70-gwanak-dreamtown",
    model: "firstHome70",
    targetPriceBand: "11억대",
    actualPriceKrw: eok(11),
    apartmentName: "관악드림타운",
    location: "서울 관악구",
    areaLabel: "24평",
    requiredCashKrw: eok(5),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(9.4),
  },
  {
    id: "firstHome70-sinjeong-jugong-1",
    model: "firstHome70",
    targetPriceBand: "11억대",
    actualPriceKrw: eok(11.8),
    apartmentName: "신정마을주공1",
    location: "서울 양천구",
    areaLabel: "24평",
    requiredCashKrw: eok(5.8),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(8.95),
  },
  {
    id: "firstHome70-cheolsan-raemian-xi",
    model: "firstHome70",
    targetPriceBand: "12억대",
    actualPriceKrw: eok(12.4),
    apartmentName: "철산래미안자이",
    location: "경기 광명시",
    areaLabel: "24평",
    requiredCashKrw: eok(6.4),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(10),
  },
  {
    id: "firstHome70-dreamforest-ipark",
    model: "firstHome70",
    targetPriceBand: "12억대",
    actualPriceKrw: eok(12.6),
    apartmentName: "꿈의숲아이파크",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(6.6),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(10.6),
  },
  {
    id: "firstHome70-gileum-newtown-6",
    model: "firstHome70",
    targetPriceBand: "13억대",
    actualPriceKrw: eok(13.3),
    apartmentName: "길음뉴타운6단지",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(7.3),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(10.3),
  },
  {
    id: "firstHome70-jangwi-xi-radiant",
    model: "firstHome70",
    targetPriceBand: "13억대",
    actualPriceKrw: eok(13.85),
    apartmentName: "장위자이레디언트",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(7.85),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: null,
  },
  {
    id: "firstHome70-ujangsan-hillstate",
    model: "firstHome70",
    targetPriceBand: "14억대",
    actualPriceKrw: eok(14.5),
    apartmentName: "우장산힐스테이트",
    location: "서울 강서구",
    areaLabel: "24평",
    requiredCashKrw: eok(8.5),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(12),
  },
  {
    id: "firstHome70-sindang-samsung",
    model: "firstHome70",
    targetPriceBand: "14억대",
    actualPriceKrw: eok(14.95),
    apartmentName: "신당동 삼성",
    location: "서울 중구",
    areaLabel: "24평",
    requiredCashKrw: eok(8.95),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(11),
  },
  {
    id: "firstHome70-lotte-castle-classia",
    model: "firstHome70",
    targetPriceBand: "15억대",
    actualPriceKrw: eok(15),
    apartmentName: "롯데캐슬클라시아",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(9),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(12.7),
  },
  {
    id: "firstHome70-raemian-cresity",
    model: "firstHome70",
    targetPriceBand: "15억대",
    actualPriceKrw: eok(15.6),
    apartmentName: "래미안크레시티",
    location: "서울 동대문구",
    areaLabel: "24평",
    requiredCashKrw: eok(11.6),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(13.52),
  },
  {
    id: "firstHome70-haengdang-hanjin-town",
    model: "firstHome70",
    targetPriceBand: "16억대",
    actualPriceKrw: eok(16.5),
    apartmentName: "행당한진타운",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(12.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.05),
  },
  {
    id: "firstHome70-sadang-woosung-2",
    model: "firstHome70",
    targetPriceBand: "16억대",
    actualPriceKrw: eok(16.7),
    apartmentName: "사당우성2",
    location: "서울 동작구",
    areaLabel: "24평",
    requiredCashKrw: eok(12.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.4),
  },
  {
    id: "firstHome70-godeok-central-ipark",
    model: "firstHome70",
    targetPriceBand: "17억대",
    actualPriceKrw: eok(17),
    apartmentName: "고덕센트럴IPARK",
    location: "서울 강동구",
    areaLabel: "24평",
    requiredCashKrw: eok(13),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.5),
  },
  {
    id: "firstHome70-sangdo-the-sharp-1",
    model: "firstHome70",
    targetPriceBand: "17억대",
    actualPriceKrw: eok(17.5),
    apartmentName: "상도더샵1차",
    location: "서울 동작구",
    areaLabel: "24평",
    requiredCashKrw: eok(13.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.9),
  },
  {
    id: "firstHome70-songpa-signature-lotte-castle",
    model: "firstHome70",
    targetPriceBand: "18억대",
    actualPriceKrw: eok(18),
    apartmentName: "송파시그니처롯데캐슬",
    location: "서울 송파구",
    areaLabel: "24평",
    requiredCashKrw: eok(14),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.3),
  },
  {
    id: "firstHome70-raemian-estium",
    model: "firstHome70",
    targetPriceBand: "18억대",
    actualPriceKrw: eok(18.5),
    apartmentName: "래미안에스티움",
    location: "서울 영등포구",
    areaLabel: "24평",
    requiredCashKrw: eok(14.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(13.9),
  },
  {
    id: "firstHome70-seoul-station-central-xi",
    model: "firstHome70",
    targetPriceBand: "19억대",
    actualPriceKrw: eok(19.4),
    apartmentName: "서울역센트럴자이",
    location: "서울 중구",
    areaLabel: "24평",
    requiredCashKrw: eok(15.4),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(16),
  },
  {
    id: "firstHome70-oksu-samsung",
    model: "firstHome70",
    targetPriceBand: "19억대",
    actualPriceKrw: eok(19.7),
    apartmentName: "옥수삼성",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(15.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.2),
  },
  {
    id: "firstHome70-centlas",
    model: "firstHome70",
    targetPriceBand: "20억대",
    actualPriceKrw: eok(20.3),
    apartmentName: "센트라스",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(16.3),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(15.3),
  },
  {
    id: "firstHome70-dangsan-central-ipark",
    model: "firstHome70",
    targetPriceBand: "20억대",
    actualPriceKrw: eok(20.5),
    apartmentName: "당산센트럴아이파크",
    location: "서울 영등포구",
    areaLabel: "24평",
    requiredCashKrw: eok(16.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(15.5),
  },
  {
    id: "firstHome70-gongdeok-xi",
    model: "firstHome70",
    targetPriceBand: "21억대",
    actualPriceKrw: eok(21.3),
    apartmentName: "공덕자이",
    location: "서울 마포구",
    areaLabel: "24평",
    requiredCashKrw: eok(17.3),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: null,
  },
  {
    id: "firstHome70-mapo-raemian-purgio",
    model: "firstHome70",
    targetPriceBand: "21억대",
    actualPriceKrw: eok(21.5),
    apartmentName: "마포래미안푸르지오",
    location: "서울 마포구",
    areaLabel: "24평",
    requiredCashKrw: eok(17.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(17),
  },
  {
    id: "firstHome70-gwacheon-purgio-summit",
    model: "firstHome70",
    targetPriceBand: "22억대",
    actualPriceKrw: eok(22.6),
    apartmentName: "과천푸르지오써밋",
    location: "경기 과천시",
    areaLabel: "24평",
    requiredCashKrw: eok(18.6),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(17.4),
  },
  {
    id: "firstHome70-gwangjang-hillstate",
    model: "firstHome70",
    targetPriceBand: "22억대",
    actualPriceKrw: eok(22.9),
    apartmentName: "광장힐스테이트",
    location: "서울 광진구",
    areaLabel: "24평",
    requiredCashKrw: eok(18.9),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(18),
  },
  {
    id: "firstHome70-oksu-parkhills",
    model: "firstHome70",
    targetPriceBand: "23억대",
    actualPriceKrw: eok(22.95),
    apartmentName: "옥수파크힐스",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(18.95),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: null,
  },
  {
    id: "firstHome70-ichon-hangaram",
    model: "firstHome70",
    targetPriceBand: "24억대",
    actualPriceKrw: eok(24.7),
    apartmentName: "이촌 한가람",
    location: "서울 용산구",
    areaLabel: "24평",
    requiredCashKrw: eok(20.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(19),
  },
  {
    id: "firstHome70-mokdong-newtown-7",
    model: "firstHome70",
    targetPriceBand: "25억대",
    actualPriceKrw: eok(25),
    apartmentName: "목동신시가지7",
    location: "서울 양천구",
    areaLabel: "24평",
    requiredCashKrw: eok(21),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(19.25),
  },
  {
    id: "general40-sk-bukhansan-city",
    model: "general40",
    targetPriceBand: "7억대",
    actualPriceKrw: eok(7),
    apartmentName: "SK북한산시티",
    location: "서울 강북구",
    areaLabel: "24평",
    requiredCashKrw: eok(4.2),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(2.8),
    peakPriceKrw: eok(7.8),
  },
  {
    id: "general40-hagye-jangmi",
    model: "general40",
    targetPriceBand: "7억대",
    actualPriceKrw: eok(7.3),
    apartmentName: "하계장미",
    location: "서울 노원구",
    areaLabel: "21평",
    requiredCashKrw: eok(4.38),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(2.92),
    peakPriceKrw: eok(7.65),
  },
  {
    id: "general40-jugong-tteuranchae",
    model: "general40",
    targetPriceBand: "8억대",
    actualPriceKrw: eok(8),
    apartmentName: "주공뜨란채",
    location: "경기 광명시",
    areaLabel: "24평",
    requiredCashKrw: eok(4.8),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(3.2),
    peakPriceKrw: eok(7.75),
  },
  {
    id: "general40-dasan-epyeon-xi",
    model: "general40",
    targetPriceBand: "8억대",
    actualPriceKrw: eok(8.4),
    apartmentName: "다산e편한세상자이",
    location: "경기 남양주",
    areaLabel: "24평",
    requiredCashKrw: eok(5.04),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(3.36),
    peakPriceKrw: eok(8.9),
  },
  {
    id: "general40-wolgye-dongsin",
    model: "general40",
    targetPriceBand: "9억대",
    actualPriceKrw: eok(8.7),
    apartmentName: "월계동신",
    location: "서울 노원구",
    areaLabel: "28평",
    requiredCashKrw: eok(5.22),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(3.48),
    peakPriceKrw: eok(7.8),
  },
  {
    id: "general40-chowon-daewon",
    model: "general40",
    targetPriceBand: "9억대",
    actualPriceKrw: eok(9.7),
    apartmentName: "초원마을대원",
    location: "경기 안양시",
    areaLabel: "24평",
    requiredCashKrw: eok(5.82),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(3.88),
    peakPriceKrw: eok(8.2),
  },
  {
    id: "general40-imundong-ssangyong",
    model: "general40",
    targetPriceBand: "10억대",
    actualPriceKrw: eok(10),
    apartmentName: "이문동 쌍용",
    location: "서울 동대문구",
    areaLabel: "24평",
    requiredCashKrw: eok(6),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(8.47),
  },
  {
    id: "general40-yeomchang-donga-1",
    model: "general40",
    targetPriceBand: "10억대",
    actualPriceKrw: eok(10.7),
    apartmentName: "염창동아1차",
    location: "서울 강서구",
    areaLabel: "24평",
    requiredCashKrw: eok(6.42),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4.28),
    peakPriceKrw: eok(8.6),
  },
  {
    id: "general40-gwanak-dreamtown",
    model: "general40",
    targetPriceBand: "11억대",
    actualPriceKrw: eok(11),
    apartmentName: "관악드림타운",
    location: "서울 관악구",
    areaLabel: "24평",
    requiredCashKrw: eok(6.6),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4.4),
    peakPriceKrw: eok(9.4),
  },
  {
    id: "general40-sinjeong-jugong-1",
    model: "general40",
    targetPriceBand: "11억대",
    actualPriceKrw: eok(11.8),
    apartmentName: "신정마을주공1",
    location: "서울 양천구",
    areaLabel: "24평",
    requiredCashKrw: eok(7.08),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4.72),
    peakPriceKrw: eok(8.95),
  },
  {
    id: "general40-cheolsan-raemian-xi",
    model: "general40",
    targetPriceBand: "12억대",
    actualPriceKrw: eok(12.4),
    apartmentName: "철산래미안자이",
    location: "경기 광명시",
    areaLabel: "24평",
    requiredCashKrw: eok(7.44),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(4.96),
    peakPriceKrw: eok(10),
  },
  {
    id: "general40-dreamforest-ipark",
    model: "general40",
    targetPriceBand: "12억대",
    actualPriceKrw: eok(12.6),
    apartmentName: "꿈의숲아이파크",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(7.56),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.04),
    peakPriceKrw: eok(10.6),
  },
  {
    id: "general40-gileum-newtown-6",
    model: "general40",
    targetPriceBand: "13억대",
    actualPriceKrw: eok(13.3),
    apartmentName: "길음뉴타운6단지",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(7.98),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.32),
    peakPriceKrw: eok(10.3),
  },
  {
    id: "general40-jangwi-xi-radiant",
    model: "general40",
    targetPriceBand: "13억대",
    actualPriceKrw: eok(13.85),
    apartmentName: "장위자이레디언트",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(8.31),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.54),
    peakPriceKrw: null,
  },
  {
    id: "general40-ujangsan-hillstate",
    model: "general40",
    targetPriceBand: "14억대",
    actualPriceKrw: eok(14.5),
    apartmentName: "우장산힐스테이트",
    location: "서울 강서구",
    areaLabel: "24평",
    requiredCashKrw: eok(8.7),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.8),
    peakPriceKrw: eok(12),
  },
  {
    id: "general40-sindang-samsung",
    model: "general40",
    targetPriceBand: "14억대",
    actualPriceKrw: eok(14.95),
    apartmentName: "신당동 삼성",
    location: "서울 중구",
    areaLabel: "24평",
    requiredCashKrw: eok(8.97),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(5.98),
    peakPriceKrw: eok(11),
  },
  {
    id: "general40-lotte-castle-classia",
    model: "general40",
    targetPriceBand: "15억대",
    actualPriceKrw: eok(15),
    apartmentName: "롯데캐슬클라시아",
    location: "서울 성북구",
    areaLabel: "24평",
    requiredCashKrw: eok(9),
    maxLoanKrw: eok(6),
    appliedLoanKrw: eok(6),
    peakPriceKrw: eok(12.7),
  },
  {
    id: "general40-raemian-cresity",
    model: "general40",
    targetPriceBand: "15억대",
    actualPriceKrw: eok(15.6),
    apartmentName: "래미안크레시티",
    location: "서울 동대문구",
    areaLabel: "24평",
    requiredCashKrw: eok(11.6),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(13.52),
  },
  {
    id: "general40-haengdang-hanjin-town",
    model: "general40",
    targetPriceBand: "16억대",
    actualPriceKrw: eok(16.5),
    apartmentName: "행당한진타운",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(12.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.05),
  },
  {
    id: "general40-sadang-woosung-2",
    model: "general40",
    targetPriceBand: "16억대",
    actualPriceKrw: eok(16.7),
    apartmentName: "사당우성2",
    location: "서울 동작구",
    areaLabel: "24평",
    requiredCashKrw: eok(12.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.4),
  },
  {
    id: "general40-godeok-central-ipark",
    model: "general40",
    targetPriceBand: "17억대",
    actualPriceKrw: eok(17),
    apartmentName: "고덕센트럴IPARK",
    location: "서울 강동구",
    areaLabel: "24평",
    requiredCashKrw: eok(13),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.5),
  },
  {
    id: "general40-sangdo-the-sharp-1",
    model: "general40",
    targetPriceBand: "17억대",
    actualPriceKrw: eok(17.5),
    apartmentName: "상도더샵1차",
    location: "서울 동작구",
    areaLabel: "24평",
    requiredCashKrw: eok(13.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(12.9),
  },
  {
    id: "general40-songpa-signature-lotte-castle",
    model: "general40",
    targetPriceBand: "18억대",
    actualPriceKrw: eok(18),
    apartmentName: "송파시그니처롯데캐슬",
    location: "서울 송파구",
    areaLabel: "24평",
    requiredCashKrw: eok(14),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.3),
  },
  {
    id: "general40-raemian-estium",
    model: "general40",
    targetPriceBand: "18억대",
    actualPriceKrw: eok(18.5),
    apartmentName: "래미안에스티움",
    location: "서울 영등포구",
    areaLabel: "24평",
    requiredCashKrw: eok(14.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(13.9),
  },
  {
    id: "general40-seoul-station-central-xi",
    model: "general40",
    targetPriceBand: "19억대",
    actualPriceKrw: eok(19.4),
    apartmentName: "서울역센트럴자이",
    location: "서울 중구",
    areaLabel: "24평",
    requiredCashKrw: eok(15.4),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(16),
  },
  {
    id: "general40-oksu-samsung",
    model: "general40",
    targetPriceBand: "19억대",
    actualPriceKrw: eok(19.7),
    apartmentName: "옥수삼성",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(15.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(14.2),
  },
  {
    id: "general40-centlas",
    model: "general40",
    targetPriceBand: "20억대",
    actualPriceKrw: eok(20.3),
    apartmentName: "센트라스",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(16.3),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(15.3),
  },
  {
    id: "general40-dangsan-central-ipark",
    model: "general40",
    targetPriceBand: "20억대",
    actualPriceKrw: eok(20.5),
    apartmentName: "당산센트럴아이파크",
    location: "서울 영등포구",
    areaLabel: "24평",
    requiredCashKrw: eok(16.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(15.5),
  },
  {
    id: "general40-gongdeok-xi",
    model: "general40",
    targetPriceBand: "21억대",
    actualPriceKrw: eok(21.3),
    apartmentName: "공덕자이",
    location: "서울 마포구",
    areaLabel: "24평",
    requiredCashKrw: eok(17.3),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: null,
  },
  {
    id: "general40-mapo-raemian-purgio",
    model: "general40",
    targetPriceBand: "21억대",
    actualPriceKrw: eok(21.5),
    apartmentName: "마포래미안푸르지오",
    location: "서울 마포구",
    areaLabel: "24평",
    requiredCashKrw: eok(17.5),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(17),
  },
  {
    id: "general40-gwacheon-purgio-summit",
    model: "general40",
    targetPriceBand: "22억대",
    actualPriceKrw: eok(22.6),
    apartmentName: "과천푸르지오써밋",
    location: "경기 과천시",
    areaLabel: "24평",
    requiredCashKrw: eok(18.6),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(17.4),
  },
  {
    id: "general40-gwangjang-hillstate",
    model: "general40",
    targetPriceBand: "22억대",
    actualPriceKrw: eok(22.9),
    apartmentName: "광장힐스테이트",
    location: "서울 광진구",
    areaLabel: "24평",
    requiredCashKrw: eok(18.9),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(18),
  },
  {
    id: "general40-oksu-parkhills",
    model: "general40",
    targetPriceBand: "23억대",
    actualPriceKrw: eok(22.95),
    apartmentName: "옥수파크힐스",
    location: "서울 성동구",
    areaLabel: "24평",
    requiredCashKrw: eok(18.95),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: null,
  },
  {
    id: "general40-ichon-hangaram",
    model: "general40",
    targetPriceBand: "24억대",
    actualPriceKrw: eok(24.7),
    apartmentName: "이촌 한가람",
    location: "서울 용산구",
    areaLabel: "24평",
    requiredCashKrw: eok(20.7),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(19),
  },
  {
    id: "general40-mokdong-newtown-7",
    model: "general40",
    targetPriceBand: "25억대",
    actualPriceKrw: eok(25),
    apartmentName: "목동신시가지7",
    location: "서울 양천구",
    areaLabel: "24평",
    requiredCashKrw: eok(21),
    maxLoanKrw: eok(4),
    appliedLoanKrw: eok(4),
    peakPriceKrw: eok(19.25),
  },
];

export function findComparisonAssetMatches({
  availableCashKrw,
  model = "firstHome70",
  limit = 5,
  maxShortfallKrw = DEFAULT_MAX_SHORTFALL_KRW,
  shortfallRatio = DEFAULT_SHORTFALL_RATIO,
}: {
  availableCashKrw: number | null;
  model?: ComparisonAssetLtvModel;
  limit?: number;
  maxShortfallKrw?: number;
  shortfallRatio?: number;
}): MatchedComparisonAsset[] {
  if (availableCashKrw === null) {
    return [];
  }

  const allowedShortfallKrw = Math.min(maxShortfallKrw, Math.floor(availableCashKrw * shortfallRatio));

  return COMPARISON_ASSETS.filter(
    (asset) => asset.model === model && asset.requiredCashKrw <= availableCashKrw + allowedShortfallKrw,
  )
    .map((asset) => ({
      ...asset,
      cashDeltaKrw: availableCashKrw - asset.requiredCashKrw,
      isWithinBudget: asset.requiredCashKrw <= availableCashKrw,
    }))
    .sort((a, b) => Math.abs(a.cashDeltaKrw) - Math.abs(b.cashDeltaKrw) || b.actualPriceKrw - a.actualPriceKrw)
    .slice(0, limit);
}

